apiVersion: v1
kind: Service
metadata:
  name: appointmentservice-service
spec:
  selector:
    app: appointmentservice-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP
