apiVersion: apps/v1
kind: Deployment
metadata:
  name: patientservice-deployment
  labels:
    app: patientservice-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: patientservice-app
  template:
    metadata:
      labels:
        app: patientservice-app
    spec:
      containers:
      - name: patientservice-container
        image: ecr/patientservicejs-app:latest
        ports:
        - containerPort: 3000
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 20
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
