apiVersion: v1
kind: Service
metadata:
  name: patientservice-service
spec:
  selector:
    app: patientservice-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP
